# Generated by Django 4.0.6 on 2022-07-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_hotelimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
    ]
